# Generated by Django 3.1.4 on 2024-11-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20241125_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('genders', models.ManyToManyField(related_name='departments', to='shop.Gender')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='departments',
            field=models.ManyToManyField(related_name='categories', to='shop.Department'),
        ),
    ]
